services:
  db1:
    container_name: db1
    image: postgres:16.6
    shm_size: 128mb
    volumes:
      - "$PWD/conf/postgresql_1.conf:/etc/postgresql/postgresql.conf"
      - "$PWD/conf/pg_hba_1.conf:/etc/postgresql/pg_hba.conf"
      - "$PWD/db1-data:/var/lib/postgresql/data"
      - "$PWD/data:/tmp/data"
    environment:
      POSTGRES_PASSWORD: super1234
      POSTGRES_USER: postgres
      POSTGRES_DB: periodic_table
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    networks:
      postgresql-net:
        ipv4_address: 172.24.0.3
  db2:
    container_name: db2
    image: postgres:16.6
    shm_size: 128mb
    links:
      - db1
    volumes:
      - "$PWD/conf/postgresql_2.conf:/etc/postgresql/postgresql.conf"
      - "$PWD/conf/pg_hba_2.conf:/etc/postgresql/pg_hba.conf"
      - "$PWD/db2-data:/var/lib/postgresql/data"
      - "$PWD/data:/tmp/data"
    environment:
      POSTGRES_PASSWORD: super1234
      POSTGRES_USER: postgres
      POSTGRES_DB: periodic_table
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    networks:
      postgresql-net:
        ipv4_address: 172.24.0.4

networks:
  postgresql-net:
    name: postgresql-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
